#### TAG DICTIONARY : Converts old tag (strings found in picture filename) to new tag(s) (used in game)

# <Chris12 - Tagsets>
init -3 python:

    img_bg = Frame("UI/img_bg.png", 0, 0, tile="integer")

    # use add_tag_hotkey() to make sure you do not overwrite existing hotkeys.
    tag_hotkeys = {
        "p" : "profile",
        "t" : "portrait",
        "w" : "waitress",
        "d" : "dancer",
        "m" : "masseuse",
        "h" : "geisha",
        "r" : "rest",
        "n" : "naked",
        "s" : "service",
        "x" : "sex",
        "a" : "anal",
        "f" : "fetish",
        "g" : "group",
        "b" : "bisexual",
        "l" : "lesbian",
        "i" : "big",
        "e" : "beast",
        "c" : "machine",
        "y" : "toy",
        "o" : "monster",
    }

    def add_tag_hotkey(key, tag):
        if len(key) != 1 : raise Exception("add_tag_hotkey key '" + key + "' is not exactly one character!")
        key = key.lower()
        if key in tag_hotkeys: raise Exception("Hotkey '" + key + "' already bound to '" + tag_hotkeys[key] + "'")
        tag_hotkeys[key] = tag
# </Chris12 - Tagsets>

init -2 python:

    # tag_dict now serves as a way to add additional 'tags light'. Basically, those tags get kept if they are already in the filename, but no buttons are available to actively influence them.
    tag_dict = {
                "gallery" : "gallery", # Used as a background for the girl's CG gallery
                "ecchi" : ("rest", "libido")
    }


    ## END OF BK ORIGINAL TAGGING TOOL

    # bk_autoadds is used to keep the rating calculation in-line with BKs. E.g. lesbian automatically gets a bisexual tag in BK

    BK_AUTOADDS = (
        ("lesbian", "bisexual"),
        ("nature", "public"),
        ("beach", "public"),
        ("town", "public")
    )

    tag_dict["_trash"] = "ignore", # Change this if you want to be able to edit trash pictures

    sorted_tag_dict_keys = sorted(tag_dict.keys(), key = lambda x : -len(x)) # gets regenerated by sanity_check()


    # With sorting_dict, you can manually override order/order2.
    sorting_dict = {
                    "portrait" : (-10, 0), # This is an example, making the portrait tag come before profile in the file name
                    "profile" : (-10, 1),
                    "constitution" : (0, 55),
                    "fight" : (0, 56),
                    }

    #### Base values

    VIDEOFORMATS = (".webm", ".mpg", ".mkv", ".avi")
    IMGFORMATS = (".jpg", ".jpeg", ".png", ".bmp", ".gif", ".webp") + VIDEOFORMATS

    girl_list = []
    search_words = ""
    copy_tags = None


    # Buttons get displayed in the same order as in the main_tags list.
    # However, output order (in the filename) is determined by order/order2. (and can be overriden with sorting_dict)
    main_tags = [
        Tag(name="profile", order=0, order2=10, tagsets=[tagset_core], variants=("card","quest","shop")),
        Tag(name="portrait", order=0, order2=0, tagsets=[tagset_core]),
        Tag(name="", tagsets=[tagset_core]),
        Tag(name="waitress", order=0, order2=20, tagsets=[tagset_core], variants="wait"),
        Tag(name="dancer", order=0, order2=30, tagsets=[tagset_core], variants="danc"),
        Tag(name="masseuse", order=0, order2=40, tagsets=[tagset_core], variants="mass"),
        Tag(name="geisha", order=0, order2=50, tagsets=[tagset_core], variants="etiquette"),
        Tag(name="", tagsets=[tagset_core]),
        Tag(name="rest", order=0, order2=60, tagsets=[tagset_core]),
        Tag(name="naked", order=0, order2=200, tagsets=[tagset_core], variants="nude"),
        Tag(name="", tagsets=[tagset_core]),
        Tag(name="service", order=0, order2=230, tagsets=[tagset_core]),
        Tag(name="sex", order=0, order2=240, tagsets=[tagset_core], variants=("fuck", "xxx")),
        Tag(name="anal", order=0, order2=250, tagsets=[tagset_core]),
        Tag(name="fetish", order=0, order2=260, tagsets=[tagset_core], variants="hardcore"),
        Tag(name="", tagsets=[tagset_core]),
        Tag(name="lesbian", order=0, order2=225, tagsets=[tagset_core]),
        Tag(name="bisexual", order=0, order2=220, tagsets=[tagset_core], variants="bis"),
        Tag(name="group", order=0, order2=210, tagsets=[tagset_core]),
        Tag(name="", tagsets=[tagset_core]),
        Tag(name="big", order=0, order2=110, tagsets=[tagset_core], variants="stallion"),
        Tag(name="beast", order=0, order2=120, tagsets=[tagset_core], variants="best"),
        Tag(name="machine", order=0, order2=130, tagsets=[tagset_core]),
        Tag(name="monster", order=0, order2=140, tagsets=[tagset_core]),
        Tag(name="", tagsets=[tagset_core])
    ]

    main_tags_idx = {tag.name : num for num, tag in enumerate(main_tags) if tag is not None and tag.name != ""} # gets regenerated by sanity_check()

    # Don't touch the following lines, they are important for girl rating.

    normal_tags = ["profile", "portrait", "rest", "waitress", "dancer", "masseuse", "geisha"]
    all_sex_acts = ["service", "sex", "anal", "fetish"]
    extended_sex_acts = ["naked", "service", "sex", "anal", "fetish", "bisexual", "group"] # Don't add "lesbian" here, ruins the rating
    all_farm_tags = ["big", "beast", "monster", "machine"]

    #### Main buttons

    tag_button_dict = {"profile" : "立绘",
                       "portrait" : "头像",
                       "waitress" : "服务员",
                       "dancer" : "舞娘",
                       "masseuse" : "按摩师",
                       "geisha" : "艺伎",
                       "rest" : "休息",

                       "naked" : "露出",
                       "service" : "性服侍",
                       "sex" : "性交",
                       "anal" : "肛交",
                       "fetish" : "皮绳愉虐",
                       "lesbian" : "百合",
                       "bisexual" : "双性恋(+F)",
                       "group" : "群交(+M)",

                       "big" : "种马",
                       "beast" : "野兽",
                       "machine" : "机器",
                       "monster" : "怪物",
                       }

    s_acts = ["service", "sex", "anal", "group", "fetish", "bisexual"]

    ## 标签相关 ##
    tag_button2_dict = {
                        "profile" : "立绘",
                        "portrait" : "头像",
                        "waitress" : "服务员",
                        "dancer" : "舞娘",
                        "masseuse" : "按摩师",
                        "geisha" : "艺伎",
                        "rest" : "休息",

                        "naked" : "露出",
                        "service" : "性服侍",
                        "sex" : "性交",
                        "anal" : "肛交",
                        "fetish" : "皮绳愉虐",
                        "lesbian" : "百合",
                        "bisexual" : "双性恋(+F)",
                        "group" : "群交(+M)",

                        "big" : "种马",
                        "beast" : "野兽",
                        "machine" : "机器",
                        "monster" : "怪物",

                        "happy" : "开心",
                        "neutral" : "平常",
                        "sad" : "悲伤",

                        "cosplay" : "cosplay",
                        "maid" : "女仆",
                        "bunny" : "兔女郎",
                        "swim" : "泳装",
                        "kimono" : "和服",

                        "strip" : "脱光衣服",
                        "sing" : "偶像",
                        "fight" : "抵抗",

                        "libido" : "性欲",
                        "sensitivity" : "敏感",
                        "obedience" : "服从",
                        "constitution" : "体格",

                        "public" : "露出",

                        "toy" : "玩具",
                        "dildo" : "振动棒",
                        "vibrator" : "震动用品",
                        "beads" : "肛珠",
                        "plug" : "肛塞",
                        "strap-on" : "穿戴假阴茎",

                        "dirty" : "邋遢",
                        "wet" : "湿漉",
                        "dom" : "强势",
                        "sub" : "顺从",

                        "kiss" : "亲吻",
                        "fondle" : "抚摸",
                        "grope" : "触摸",
                        "finger" : "手指",
                        "masturbate" : "自慰",

                        "handjob" : "手交",
                        "titjob" : "乳交",
                        "footjob" : "足交",
                        "oral" : "口交",
                        "deep" : "深喉",
                        "sixty-nine" : "69",

                        "doggy" : "后背位",
                        "cowgirl" : "骑乘位",
                        "piledriver" : "打桩机",
                        "spooning" : "侧身位",
                        "double" : "双穴插入",

                        "bondage" : "绳缚",
                        "gag" : "口塞",
                        "spanking" : "打屁股",
                        "rimming" : "毒龙钻",
                        "fisting" : "拳交",
                        "lactation" : "强制泌乳",
                        "watersports" : "'水'类运动",
                        "enema" : "灌肠",

                        "cumshot" : "射精",
                        "on-body" : "射身上",
                        "on-face" : "颜射",
                        "in-hair" : "射到头发上",
                        "in-mouth" : "口暴",
                        "inside" : "内射",
                        "creampie" : "外射",
                        "bukkake" : "多人颜射",
                        "cum-shower" : "精子浴",

                        "orgasm" : "高潮",
                        "denied" : "禁止高潮",
                        "squirt" : "潮吹",
                        "advertise": "广告",

                        "total" : "总计",
                        }

    ## 特质相关 ##
    trait_name_dict = {
                       ## 黄金特质 ##
                       "Naughty" : "放荡不羁",
                       "Fascinating" : "得心应手",
                       "Lust" : "如狼似虎",
                       "Warrior" : "锐不可当",
                       "Skilled tongue" : "巧舌如簧",
                       "Always wet" : "欲壑难填",
                       "Tight ass" : "后门紧致",
                       "Playful" : "妙趣横生",
                       "Wild" : "桀骜不驯",
                       "Dirty mind" : "不知耻辱",
                       "Magnetic" : "财运亨通",
                       "Loose" : "肆无忌惮",
                       "Dedicated" : "兢兢业业",
                       "Provocative" : "妙语连珠",
                       "Fashionista" : "时尚达人",
                       "Perfectionist" : "精益求精",
                       "Elite" : "精明能干",
                       "Gifted" : "天赋异禀",
                       "Fast learner" : "举一反三",
                       "Caster" : "莫测高深",
                       "Driven" : "精力充沛",
                       "Country girl" : "乡下姑娘",
                       "Noble" : "大家风范",
                       "Naturist" : "返璞归真",
                       "Vicious" : "任情恣性",

                       ## 正面特质 ##
                       "Cute" : "率真可爱",
                       "Long legs" : "纤纤玉腿",
                       "Nice boobs" : "波涛汹涌",
                       "Juicy ass" : "蜂腰肥臀",
                       "Sweet" : "柔情蜜意",
                       "Exotic" : "异国风情",
                       "Polite" : "知书达理",
                       "Feminine" : "风姿绰约",
                       "Horny" : "天生媚骨",
                       "Resilient" : "精神焕发",
                       "Delicate" : "玉软花柔",
                       "Meek" : "温文尔雅",

                       "Pretty eyes" : "盈盈秋水",
                       "Firm tits" : "呼之欲出",
                       "Seductive" : "秀外慧中",
                       "Graceful" : "芳兰竟体",

                       "Beautiful" : "国色天香",
                       "Fit" : "长身玉立",
                       "Charming" : "妩媚多姿",
                       "Elegant" : "才望高雅",
                       "Slutty" : "天生媚骨",
                       "Athletic" : "刚劲有力",
                       "Sensitive" : "心细如发",
                       "Obedient" : "奴颜媚骨",

                       "Energetic" : "活力四射",
                       "Tough" : "钢筋铁骨",
                       "Sexy" : "人间尤物",
                       "Humble" : "戒奢宁俭",

                       "Virgin" : "白璧无瑕",
                       "Sharp" : "手不释卷",
                       "Loyal" : "心心相印",
                       "Brave" : "无所畏惧",
                       "Strong" : "身强力壮",
                       "Lucky" : "吉星高照",

                       "Deft" : "慧心灵性",
                       "Nimble" : "手脚麻利",
                       "Soft skin" : "肤如凝脂",
                       "Bright" : "如沐春风",
                       "Agile" : "眼明手捷",
                       "Brisk" : "身轻如燕",

                       "Rowdy" : "能言善辩",
                       "Powerful" : "搔首弄姿",
                       "Unhurried" : "从容不迫",
                       "Modest" : "典则俊雅",

                       "Sensual" : "声色犬马",
                       "Kinky" : "奇技淫巧",
                       "Pervert" : "自甘堕落",
                       "Thief" : "妙手空空",

                       ## 负面特质 ##
                       "Plain" : "臼头深目",
                       "Scars" : "遍体鳞伤",
                       "Mean" : "刁钻刻薄",
                       "Rude" : "鲁莽灭裂",
                       "Cold" : "冷若冰霜",
                       "Weak" : "瘦骨嶙峋",
                       "Rough" : "才短气粗",
                       "Defiant" : "目中无人",

                       "Scruffy" : "不修边幅",
                       "Plump" : "体态臃肿",
                       "Timid" : "烟视媚行",
                       "Vulgar" : "蛮横无理",
                       "Tame" : "百无聊赖",
                       "Frail" : "饱食终日",
                       "Jaded" : "多愁善感",
                       "Rebellious" : "顽冥不灵",

                       "Lazy" : "好吃懒做",
                       "Sickly" : "弱不禁风",
                       "Homely" : "相貌平平",
                       "Expensive" : "挥金如土",

                       "Slow" : "呆头呆脑",
                       "Distrustful" : "疑神疑鬼",
                       "Fearful" : "胆小如鼠",
                       "Vulnerable" : "不堪一击",
                       "Unlucky" : "命途多舛",

                       "All thumbs" : "笨手笨脚",
                       "Awkward" : "手忙脚乱",
                       "Brutal" : "揎拳捰袖",
                       "Dumb" : "拙嘴笨舌",
                       "Oafish" : "天生残疾",
                       "Clumsy" : "愚不可及",

                       "Prude" : "装腔作势",
                       "Naive" : "未经人事",
                       "Square" : "道貌岸然",

                       ## 特殊特质 ##
                       "Godless" : "敬而远之",
                       "Housebroken" : "恬不知耻",
                       "Teacher's pet" : "入室弟子",
                       "Trauma" : "黯然神伤",
                       "Farmgirl" : "农场之星",

                       ## 故事特质 ##
                       "Dynamo" : "Dynamo",
                       "Lolita" : "娇小玲珑",
                       "Ghost" : "野鬼孤魂",
                       "Stalwart" : "勇猛精进",

                       "Firebound" : "野火燎原",
                       "Voidbound" : "虚无缥缈",
                       "Waterbound" : "翻江倒海",
                       "Earthbound" : "地动山摇",
                       }

    ## 女孩相关 ##
    girl_related_dict = {
                        ## 统计名称 ##
                        "Beauty" : "美貌",
                        "beauty" : "美貌",
                        "Body" : "身材",
                        "body" : "身材",
                        "Charm" : "魅力",
                        "charm" : "魅力",
                        "Refinement" : "优雅",
                        "refinement" : "优雅",
                        "Sensitivity" : "敏感",
                        "sensitivity" : "敏感",
                        "Libido" : "性欲",
                        "libido" : "性欲",
                        "Constitution" : "体格",
                        "constitution" : "体格",
                        "Obedience" : "服从",
                        "obedience" : "服从",
                        "Service" : "性服侍",
                        "service" : "性服侍",
                        "Sex" : "性交",
                        "sex" : "性交",
                        "Anal" : "肛交",
                        "anal" : "肛交",
                        "Fetish" : "皮绳愉虐",
                        "fetish" : "皮绳愉虐",
                        "Energy" : "精力",
                        "energy" : "精力",

                        ## 职业名称 ##
                        "Waitress" : "服务员",
                        "waitress" : "服务员",
                        "Dancer" : "舞娘",
                        "dancer" : "舞娘",
                        "Masseuse" : "按摩师",
                        "masseuse" : "按摩师",
                        "Geisha" : "艺伎",
                        "geisha" : "艺伎",
                        "Whore" : "妓女",
                        "whore" : "妓女",

                        ## 性行为 ##
                        "Service" : "性服侍",
                        "service" : "性服侍",
                        "Sex" : "性交",
                        "sex" : "性交",
                        "Anal" : "肛交",
                        "anal" : "肛交",
                        "Fetish" : "皮绳愉虐",
                        "fetish" : "皮绳愉虐",
                        "Naked" : "露出",
                        "naked" : "露出",
                        "Group" : "群交",
                        "group" : "群交",
                        "Bisexual" : "百合",
                        "bisexual" : "百合",

                        ## 偏好 ##
                        "Refuses" : "抵制",
                        "refuses" : "抵制",
                        "Very reluctant" : "非常不情愿",
                        "very reluctant" : "非常不情愿",
                        "Reluctant" : "不情愿",
                        "reluctant" : "不情愿",
                        "A little reluctant" : "有点不情愿",
                        "a little reluctant" : "有点不情愿",
                        "Indifferent" : "不在意",
                        "indifferent" : "不在意",
                        "A little interested" : "有点感兴趣",
                        "a little interested" : "有点感兴趣",
                        "Interested" : "感兴趣",
                        "interested" : "感兴趣",
                        "Very interested" : "非常感兴趣",
                        "very interested" : "非常感兴趣",
                        "Fascinated" : "陶醉",
                        "fascinated" : "陶醉",

                        ## 反应 ##
                        "ambivalent feelings" : "感到矛盾",
                        "a weakness" : "是她的弱点",
                        "a disgust" : "感到厌恶",
                        "no particular reaction" : "没什么特别的反应",

                        ## 癖好 ##
                        "Stripping" : "脱光衣服",
                        "stripping" : "脱光衣服",
                        "Public acts" : "公开play",
                        "public acts" : "公开play",
                        "Cosplay" : "穿着cosplay服装",
                        "cosplay" : "穿着cosplay服装",
                        "Dildos" : "使用假阳具",
                        "dildos" : "使用假阳具",
                        "Vibrators" : "使用跳蛋",
                        "vibrators" : "使用跳蛋",
                        "Dirty sex" : "就地性交",
                        "dirty sex" : "就地性交",
                        "Penis worship" : "服侍肉棒",
                        "penis worship" : "服侍肉棒",
                        "Bondage" : "麻绳束缚",
                        "bondage" : "麻绳束缚",
                        "Oil" : "精油按摩",
                        "oil" : "精油按摩",
                        "Wet" : "被淋湿",
                        "wet" : "被淋湿",
                        "Submission" : "羞辱",
                        "submission" : "羞辱",
                        "Femdom" : "女方主导",
                        "femdom" : "女方主导",
                        "Gags" : "戴上口塞",
                        "gags" : "戴上口塞",
                        "Strap-ons" : "穿戴阳具",
                        "strap-ons" : "穿戴阳具",
                        "Roleplay" : "角色扮演",
                        "roleplay" : "角色扮演",
                        "Plugs" : "使用肛塞",
                        "plugs" : "使用肛塞",
                        "Enemas" : "灌肠",
                        "enemas" : "灌肠",
                        "Beads" : "使用肛门拉珠",
                        "beads" : "使用肛门拉珠",

                        "Masturbation" : "自慰",
                        "masturbation" : "自慰",
                        "Fingering" : "手指插入",
                        "fingering" : "手指插入",
                        "Handjobs" : "手交",
                        "handjobs" : "手交",
                        "Cunnilingus" : "舔阴",
                        "cunnilingus" : "舔阴",
                        "Oral" : "口交",
                        "oral" : "口交",
                        "Irrumatio" : "强制口交",
                        "irrumatio" : "强制口交",
                        "Deep throat" : "深喉",
                        "deep throat" : "深喉",
                        "Titjobs" : "乳交",
                        "titjobs" : "乳交",
                        "Footjobs" : "足交",
                        "footjobs" : "足交",
                        "Double penetration" : "双穴插入",
                        "double penetration" : "双穴插入",
                        "Fisting" : "拳交",
                        "fisting" : "拳交",
                        "Insults" : "语言辱骂",
                        "insults" : "语言辱骂",
                        "69" : "69",
                        "Watersports" : "尿浴",
                        "watersports" : "尿浴",
                        "Ass-to-mouth" : "肛交后口交",
                        "ass-to-mouth" : "肛交后口交",
                        "Kissing" : "亲吻她",
                        "kissing" : "亲吻她",
                        "Spanking" : "打屁股",
                        "spanking" : "打屁股",
                        "Rimming" : "毒龙钻",
                        "rimming" : "毒龙钻",
                        "Fondling her boobs" : "抚弄乳房",
                        "fondling her boobs" : "抚弄乳房",
                        "Groping her ass" : "抚弄肛门",
                        "groping her ass" : "抚弄肛门",
                        "Lactation" : "强制泌乳",
                        "lactation" : "强制泌乳",
                        "Doggy style" : "后背位",
                        "doggy style" : "后背位",
                        "Cowgirl" : "骑乘位",
                        "cowgirl" : "骑乘位",
                        "Piledriver" : "抬单腿后背位",
                        "piledriver" : "抬单腿后背位",
                        "Spooning" : "侧身位",
                        "spooning" : "侧身位",

                        "Bukkake" : "多人颜射",
                        "bukkake" : "多人颜射",
                        "Cum in mouth" : "口暴",
                        "cum in mouth" : "口暴",
                        "Cum on face" : "颜射",
                        "cum on face" : "颜射",
                        "Cum in hair" : "射到头发上",
                        "cum in hair" : "射到头发上",
                        "Cum on body" : "射到身上",
                        "cum on body" : "射到身上",
                        "Cum shower" : "精子浴",
                        "cum shower" : "精子浴",
                        "Swallowing" : "深喉射",
                        "swallowing" : "深喉射",
                        "Creampie" : "外射",
                        "creampie" : "外射",
                        "Cum inside" : "内射",
                        "cum inside" : "内射",
                        "Multiple orgasms" : "多重高潮",
                        "multiple orgasms" : "多重高潮",
                        "Denied orgasm" : "禁止高潮",
                        "denied orgasm" : "禁止高潮",
                        "Squirting" : "潮吹",
                        "squirting" : "潮吹",

                        ## 杂项 ##
                        "Color" : "颜色",
                        "color" : "颜色",
                        "Food" : "食物",
                        "food" : "食物",
                        "Drink" : "饮料",
                        "drink" : "饮料",
                        None : "(girl_related_dict)没有值",
                        }

    ## 性格相关 ##
    personalities_related_dict = {
                                 "Pervert" : "变态",
                                 "Rebel" : "叛逆",
                                 "Cold" : "冰冷",
                                 "Nerd" : "书呆子",
                                 "Masochist" : "受虐狂",
                                 "Meek" : "温顺",
                                 "Sweet" : "甜美",
                                 "Superficial" : "肤浅",
                                 "Bimbo" : "荡妇",
                                 "Holy" : "圣洁",
                                 "Helper" : "热心",
                                 "Creep" : "害羞",
                                 "Repressed" : "压抑",
                                 "Schemer" : "谋士",
                                 "Prude" : "傲慢",
                                 "Princess" : "公主",
                                 "Pet" : "宠物",
                                 "Easy" : "安逸",
                                 "Class president" : "班长",
                                 "Tsundere" : "傲娇",
                                 "Loyal" : "忠诚",
                                 "Yandere" : "病娇",
                                 "Stubborn" : "顽固",
                                 }

    # The optional_tag_dict is specific to this naming tool. It sets some rules for when to show/hide optional tags
    optional_tags = [
            Tag(name="happy", order=7, order2=1),
            Tag(name="neutral", order=7, order2=2),
            Tag(name="sad", order=7, order2=3),

            Tag(name="cosplay", order=10, order2=0, variants=("roleplay", "role")),
            Tag(name="maid", _or=("profile", "portrait", "waitress"), order=10, order2=1, auto_add="waitress"),
            Tag(name="bunny", _or=("profile", "portrait", "waitress"), order=10, order2=1, auto_add="waitress"),
            Tag(name="swim", _or=("profile", "portrait", "masseuse", "rest"), order=10, order2=2),
            Tag(name="kimono", _or=("profile", "portrait", "geisha"), order=10, order2=3, auto_add="geisha"),

            Tag(name="strip", order=15, order2=1, fix_name="stripping"),
            Tag(name="sing", order=15, _or="dancer", _not = s_acts+all_farm_tags, order2=2, auto_add="dancer"),
            Tag(name="fight", order=15, _not = s_acts+all_farm_tags, order2=3, variants=["combat", "battle"]),

            Tag(name="libido", order=20, order2=1),
            Tag(name="sensitivity", order=20, order2=2),
            Tag(name="obedience", _not = s_acts, order=20, order2=3),
            Tag(name="constitution", _not = s_acts, order=20, order2=4, variants="run"),

            Tag(name="public", order=25, order2=0, fix_name="public acts"),

            Tag(name="toy", order=30, order2=0),
            Tag(name="dildo", _or="toy", order=30, order2=1, fix_name="dildos", auto_add="toy", variants="dild"),
            Tag(name="vibrator", _or=("fetish", "toy"), order=30, order2=2, fix_name="vibrators", auto_add="toy", variants="vibr"),
            Tag(name="beads", _or=("fetish", "anal", "toy"), order=30, order2=3, auto_add="toy", variants="bead"),
            Tag(name="plug", _or=("fetish", "anal", "toy"), order=30, order2=4, fix_name="plugs", auto_add="toy"),
            Tag(name="strap-on", _or=("bisexual", "lesbian", "group"), _and=("toy"), order=30, order2=9, fix_name="strap-ons", variants="strap"),

            Tag(name="dirty", _or=extended_sex_acts, order=40, order2=12, fix_name="dirty sex"),
            Tag(name="wet", order=40, order2=14, variants="oil"),
            Tag(name="dom", order=40, order2=15, fix_name="femdom"),
            Tag(name="sub", order=40, order2=16, fix_name="submission", variants=("humiliat", "insults")),

            Tag(name="kiss", order=50, order2=1, fix_name="kissing"),
            Tag(name="fondle", _or = s_acts + ["naked"], order=50, order2=2, fix_name="fondling her boobs", variants="fondl"),
            Tag(name="grope", _or = s_acts + ["naked"], order=50, order2=3, fix_name="groping her ass", variants="grop"),
            Tag(name="finger", _or=("naked", "service", "bisexual", "fetish", "group"), order=50, order2=4, fix_name="fingering"),
            Tag(name="masturbate", _or = ("rest", "service", "naked", "sex"), order=50, order2=5, shorthand="mast", fix_name="masturbation"),

            Tag(name="handjob", _or=("service", "group"), order=60, order2=4, fix_name="handjobs", variants=("hand", "penis worship", "penis-worship", "penis_worship", "penisworship", "penis w", "penis-w", "penis_w", "penisw")),
            Tag(name="titjob", _or=("service", "group"), order=60, order2=5, fix_name="titjobs", variants=("titj", "ttj", "tits", "titty")),
            Tag(name="footjob", _or=("service", "fetish"), order=60, order2=6, fix_name="footjobs", variants=("foot", "fj")),
            Tag(name="oral", _or=("service", "bisexual", "group"), order=60, order2=7, variants=("blowjob", "bj")),
            Tag(name="deep", _or=("service", "group"), order=60, order2=8, fix_name="deep throat", variants=("irru", "dt")),
            Tag(name="sixty-nine", _or=("service", "bisexual"), order=60, order2=9, variants=("69 ", "sixty"), fix_name="69"),

            Tag(name="doggy", _or=("sex", "anal"), order=70, order2=14, fix_name="doggy style"),
            Tag(name="cowgirl", _or=("sex", "anal"), order=70, order2=15, variants="cowg"),
            Tag(name="piledriver", _or=("sex", "anal"), order=70, order2=16, variants = "pile"),
            Tag(name="spooning", _or=("sex", "anal"), order=70, order2=17, variants = "spoon"),
            Tag(name="double", _or="group", order=70, order2=18, fix_name="double penetration"),

            Tag(name="bondage", _or=("fetish", "naked"), order=80, order2=1, variants="bdsm"),
            Tag(name="gag", _or=("fetish", "naked"), order=80, order2=2, fix_name="gags"),
            Tag(name="spanking", _or=("fetish", "anal"), order=80, order2=3, variants="spank"),
            Tag(name="rimming", _or=("service", "fetish"), order=80, order2=4, variants="rim"),
            Tag(name="fisting", _or=("fetish", "bisexual", "anal"), order=80, order2=5, variants="fist"),
            Tag(name="lactation", _or=("naked", "fetish"), order=80, order2=6, variants="lact"),
            Tag(name="watersports", _or=("fetish", "sex"), order=80, order2=7, fix_name="watersports", lbl="Watersp", variants="watersp"),
            Tag(name="enema", _or=("fetish", "anal", "toy"), order=80, order2=8, fix_name="enemas"),

            Tag(name="cumshot", order=90, order2=1),
            Tag(name="on-body", _or="cumshot", order=90, order2=2, shorthand="cob", fix_name="cum on body", variants="body", auto_add="cumshot"),
            Tag(name="on-face", _or="cumshot", order=90, order2=3, shorthand="cof", fix_name="cum on face", variants="face", auto_add="cumshot"),
            Tag(name="in-hair", _or="cumshot", order=90, order2=4, shorthand="cih", fix_name="cum in hair", variants="hair", auto_add="cumshot"),
            Tag(name="in-mouth", _or="cumshot", order=90, order2=5, shorthand="cim", fix_name="cum in mouth", variants=("mouth", "swallow"), auto_add="cumshot"),
            Tag(name="inside", _or=("sex", "anal", "group"), _and="cumshot", order=90, order2=8, shorthand="cin", fix_name="cum inside", auto_add="cumshot"),
            Tag(name="creampie", _or=("sex", "anal", "group"), _and="cumshot", order=90, order2=9, variants="cream", auto_add="cumshot"),
            Tag(name="bukkake", _or=("bisexual", "group"), _and="cumshot", order=90, order2=10, shorthand="bukk", auto_add="cumshot"),
            Tag(name="cum-shower", _or=("bisexual", "group"), _and="cumshot", order=90, order2=11, lbl="Cumshower", variants=("cum shower", "shower"), auto_add="cumshot"),

            Tag(name="orgasm", order=100, _not="denied", order2=1, fix_name="multiple orgasms"),
            Tag(name="denied", order=100, _not="orgasm", order2=2, fix_name="denied orgasm"),
            Tag(name="squirt", _or="orgasm", order=100, order2=3, fix_name="squirting", auto_add="orgasm"),
    ]
    optional_tags = sorted(optional_tags, key = lambda x: (x.order, x.order2)) # gets regenerated by sanity_check()
    optional_tag_dict = {tag.name : tag for tag in optional_tags} # gets regenerated by sanity_check()

    all_tags_dict = {tag.name : tag for tag in (main_tags + optional_tags)} # gets regenerated by sanity_check()

    # This is a copy of BK's original Fixation dictionary (for girl pack stats calculations)
    fix_dict = {
                "stripping" : Fixation("stripping", acts=("naked", "sex", "bisexual"), step=1, attribute="repressed", tag_list=("strip", "naked", "dancer"), not_list=["naked"]),
                "public acts" : Fixation("public acts", acts=("naked", "service", "sex", "group"), step=1, attribute="extravert", tag_list=(["public"],)),
                "cosplay" : Fixation("cosplay", acts=("naked", "fetish", "bisexual"), step=1, attribute="extravert", tag_list=(["cosplay"], ["maid", "kimono"], ["swim", "waitress", "dancer"]), not_list=["naked"],),
                "dildos" : Fixation("dildos", acts=("sex", "anal", "bisexual"), step=1, attribute="introvert", tag_list=(["dildo"], ["toy"],)),
                "vibrators" : Fixation("vibrators", acts=("naked", "fetish", "bisexual"), step=1, attribute="introvert", tag_list=(["vibrator"], ["toy"],)),
                "dirty sex" : Fixation("dirty sex", acts=("sex", "fetish", "group"), step=1, attribute="sub", tag_list=(["dirty"],)),
                "penis worship" : Fixation("penis worship", acts=("service", "group"), step=1, attribute="sub", tag_list=(["handjob"], ["big"],)),
                "bondage" : Fixation("bondage", acts=("fetish", "naked"), step=1, attribute="sub", tag_list=(["bondage"],)),
                "oil" : Fixation("oil", acts=("group", "anal"), step=1, attribute="extravert", tag_list=(["wet"],)),
                "wet" : Fixation("wet", acts=("naked", "sex", "bisexual"), step=1, attribute="extravert", tag_list=(["wet"],)),
                "submission" : Fixation("submission", acts=("service", "fetish", "bisexual"), step=1, attribute="sub", tag_list=(["sub"],)),
                "femdom" : Fixation("femdom", acts=("bisexual", "sex", "service"), step=1, attribute="dom", tag_list=(["dom"],)),
                "gags" : Fixation("gags", acts=("fetish", "naked"), step=1, attribute="introvert", tag_list=(["gag"], ["bondage"],)),
                "strap-ons" : Fixation("strap-ons", acts=("bisexual", "group"), step=1, attribute="dom", tag_list=(["strap-on"], ["lesbian"], ["toy"],)),
                "roleplay" : Fixation("roleplay", acts=("naked", "sex", "fetish"), step=1, attribute="extravert", tag_list=(["cosplay"], ["maid", "kimono"], ["swim", "waitress", "dancer"])),
                "plugs" : Fixation("plugs", acts=("naked", "anal"), step=1, attribute="repressed", tag_list=(["plug"], ["toy"],)),
                "enemas" : Fixation("enemas", acts=("group", "anal"), step=1, attribute="materialist", tag_list=(["enema"], ["toy"],)),
                "beads" : Fixation("beads", acts=("anal"), step=1, attribute="introvert", tag_list=(["beads"], ["toy"],)),

                "masturbation" : Fixation("masturbation", acts=("service", "naked", "sex"), step=2, attribute="extravert", tag_list=(["masturbate"], ["naked"],)),
                "fingering" : Fixation("fingering", acts=("naked", "fetish", "bisexual", "group"), step=2, attribute="lewd", tag_list=(["finger"],)),
                "handjobs" : Fixation("handjobs", acts=("service", "group"), step=2, attribute="repressed", tag_list=(["handjob"],)),
                "cunnilingus" : Fixation("cunnilingus", acts=("service", "bisexual"), step=2, attribute="introvert", tag_list=(["cunnilingus"],["finger"])),
                "oral" : Fixation("oral", acts=("service", "bisexual", "group"), step=2, tag_list=(["oral"],)),
                "irrumatio" : Fixation("irrumatio", acts=("fetish"), step=2, attribute="sub", tag_list=(["deep"], ["oral"],)),
                "deep throat" : Fixation("deep throat", acts=("service", "group"), step=2, attribute="sub", tag_list=(["deep"], ["oral"],)),
                "titjobs" : Fixation("titjobs", acts=("service", "group"), step=2, attribute="extravert", tag_list=(["titjob"],)),
                "footjobs" : Fixation("footjobs", acts=("service", "fetish"), step=2, attribute="dom", tag_list=(["footjob"],)),
                "double penetration" : Fixation("double penetration", acts=("group"), step=2, attribute="lewd", tag_list=(["double"],)),
                "fisting" : Fixation("fisting", acts=("fetish", "bisexual", "anal"), step=2, attribute="lewd", tag_list=(["fisting"], ["finger"])),
                "insults" : Fixation("insults", acts=("fetish", "naked"), step=2, attribute="sub", tag_list=(["sub"],)),
                "69" : Fixation("69", acts=("service", "bisexual"), step=2, attribute="dom", tag_list=(["sixty-nine"], ["oral"],)),
                "watersports" : Fixation("watersports", acts=("fetish", "sex"), step=2, attribute="sub", tag_list=(["watersports"], ["squirt"],)),
                "ass-to-mouth" : Fixation("ass-to-mouth", acts=("anal", "group"), step=2, attribute="sub", tag_list=(["in-mouth"], ["oral"],)),
                "kissing" : Fixation("kissing", acts=("naked", "sex", "bisexual"), step=2, attribute="idealist", tag_list=(["kiss"],)),
                "spanking" : Fixation("spanking", acts=("fetish", "anal"), step=2, attribute="sub", tag_list=(["spanking"], ["sub"],)),
                "rimming" : Fixation("rimming", acts=("service", "fetish"), step=2, attribute="sub", tag_list=(["rimming"],)),
                "fondling her boobs" : Fixation("fondling her boobs", short_name = "fondling", acts=("naked", "sex", "bisexual", "group"), step=2, tag_list=(["fondle"],)),
                "groping her ass" : Fixation("groping her ass", short_name = "groping", acts=("naked", "anal", "bisexual", "group"), step=2, tag_list=(["grope"],)),
                "lactation" : Fixation("lactation", acts=("naked", "fetish"), step=2, attribute="extravert", tag_list=(["lactation"], ["titjob"],)),
                "doggy style" : Fixation("doggy style", acts=("sex", "anal"), step=2, attribute="lewd", tag_list=(["doggy"],)),
                "cowgirl" : Fixation("cowgirl", acts=("sex", "anal"), step=2, attribute="dom", tag_list=(["cowgirl"],)),
                "piledriver" : Fixation("piledriver", acts=("sex", "anal"), step=2, attribute="materialist", tag_list=(["piledriver"],)),
                "spooning" : Fixation("spooning", acts=("sex", "anal"), step=2, attribute="idealist", tag_list=(["spooning"],)),

                "bukkake" : Fixation("bukkake", acts=("bisexual", "group"), step=3, attribute="lewd", tag_list=(["bukkake"], ["on-face"], ["cumshot"],)),
                "cum in mouth" : Fixation("cum in mouth", acts=("service", "anal", "bisexual"), step=3, attribute="lewd", tag_list=(["in-mouth"], ["oral"],)),
                "cum on face" : Fixation("cum on face", acts=("service", "sex", "fetish"), step=3, attribute="sub", tag_list=(["on-face"], ["bukkake"], ["cumshot"],)),
                "cum in hair" : Fixation("cum in hair", acts=("service", "fetish"), step=3, attribute="sub", tag_list=(["in-hair"], ["on-face", "bukkake"], ["cumshot"],)),
                "cum on body" : Fixation("cum on body", acts=("sex", "anal", "service"), step=3, attribute="dom", tag_list=(["on-body"], ["cumshot"],)),
                "cum shower" : Fixation("cum shower", acts=("bisexual", "group"), step=3, attribute="sub", tag_list=(["cum-shower"], ["on-body", "in-hair"], ["cumshot"],)),
                "swallowing" : Fixation("swallowing", acts=("service", "fetish"), step=3, attribute="materialist", tag_list=(["in-mouth"], ["deep"], ["oral"],)),
                "creampie" : Fixation("creampie", acts=("sex", "anal", "group"), step=3, attribute="extravert", tag_list=(["creampie"], ["inside"],)),
                "cum inside" : Fixation("cum inside", acts=("sex", "anal"), step=3, attribute="introvert", tag_list=(["inside"], ["creampie"],)),
                "multiple orgasms" : Fixation("multiple orgasms", acts=("group", "bisexual"), step=3, attribute="lewd", tag_list=(["orgasm"],)),
                "denied orgasm" : Fixation("denied orgasm", acts=("anal", "fetish", "bisexual"), step=3, attribute="sub", tag_list=(["denied"],)),
                "squirting" : Fixation("squirting", acts=("service", "sex", "bisexual"), step=3, attribute="extravert", tag_list=(["squirt"], ["watersport", "orgasm"],)),
                }



    event_color = {"special": "{color=#FF9900}%s{/color}",
                   "good": "{color=#009874}%s{/color}",
                   "a little good": "{color=#66FF99}%s{/color}",
                   "average": "{color=#FFFF33}%s{/color}",
                   "a little bad": "{color=#F78181}%s{/color}",
                   "bad": "{color=#FF0000}%s{/color}",
                   "fear": "{color=#9933FF}%s{/color}",
                   }


    tag_main_help = {
                    "machine" : "{b}machine{/b}机器图片显示女孩带着机器人或机械装置自主运动。\n对于普通的性玩具，包括振动棒，请改用“玩具”标签。",
                    "bisexual" : "{b}bisexual{/b}图片中至少还有一名女性。只有女性的图片应该被标记为“女同性恋”。\n双性恋图片使用额外的性标签，例如您可以标记“双性恋+皮绳愉虐”。",
                    "group" : "{b}bisexual{/b}图片中至少有一个人。如果包含男性和女性，请将此标签与“双性恋”结合起来。\n同组图片可以使用额外性标签，例如您可以标记“群交 性服侍 肛交”。\n“群交”标签也适用于农场中的非人类仆从。",
                    ("profile", "portrait") : "{b}立绘{/b}图片显示了女孩的整个身体，{b}头像{/b}专注于面部。 这些图片应该只显示女孩，没有其他人。如果没有其他匹配的图片可用，则使用默认立绘和头像图片。它们应该有裸体和非裸体两种版本，以及可以有快乐/悲伤/性欲等等版本",
                    "waitress" : "{b}waitress{/b}服务员的图片应该有裸体和非裸体两种版本。\n例子提供食物或饮料、做饭或清洁的女孩。\n如果与性标签一起使用，则不会在正常工作期间显示，但可能会在工作、妓女以及特殊事件期间显示。",
                    "dancer" : "{b}dancer{/b}舞娘图片应该有裸体和非裸体两种版本。\n例子女孩跳舞、唱歌、脱衣、穿着舞者般的服装或内衣。\n如果与性标签一起使用，则不会在正常工作期间显示，但可能会在工作、妓女以及特殊事件期间显示。",
                    "masseuse" : "{b}masseuse{/b}按摩师图片应该有裸体和非裸体两种版本。\n例如女孩只穿着毛巾或泳衣，或靠近浴缸或游泳池。\n如果与性标签一起使用，则不会在正常工作期间显示，但可能会在工作、妓女以及特殊事件期间显示。",
                    "geisha" : "{b}geisha{/b}艺妓图片应该有裸体和非裸体两种版本。\n例如女孩穿着传统或花哨的服装，如和服或鸡尾酒礼服。\n如果与性标签一起使用，则不会在正常工作期间显示，但可能会在工作、妓女以及特殊事件期间显示。",
                    "rest" : "{b}rest{/b}休息图片应该有裸体和非裸体两种版本。\n例子躺在床上或坐在椅子上。\n如果与性标签一起使用，则不会在正常休息时显示。",
                    "naked" : "{b}naked{/b}女孩赤裸上身，露出她的生殖器/屁眼，或者她是全裸。\n使用 'strip' 或 'libido' 标签来代替更模糊的情况。\n强烈建议使用立绘、头像、休息、工作和农场标签的裸体变体。\n不建议将裸体标签用于性爱图片（所有性爱图片均假定为裸体）。",
                    ("beast", "monster") : "{b}beast{/b}野兽是自然界的动物，{b}monster{/b}怪物是超自然的。野兽和怪物图片仅限于游戏中的农场。农场图片通常不使用可选标签。",
                    "service" : "{b}service{/b}性服务图片包括自慰、手交、口交、乳交和其他种类的基本前戏行为。",
                    "fetish" : "{b}fetish{/b}皮绳愉虐图片显示了不容易归入其他性别类别的各种扭结，例如绳缚、拳交或足交。",
                    ("sex", "anal") : "{b}sex{/b}性交涉及男性生殖器官对阴道的性插入。 {b}anal{/b}肛交涉及男性生殖器官对肛门的性插入。（废话。原文就有这个吐槽哈哈哈）应用'sex' 和'anal' 来表示'could be either'。\n如果插入即将发生或明显更早发生也可以应用标签。百合图片的条件略有调整。",
                    "big" : "{b}big{/b}大鸡巴图片涉及男性拥有比一般更大的公鸡。 或者一个拥有超凡脱俗身体的男性。",
                    # 下面部分后面那段原话,不知道怎么翻译:{b}Sex{/b} and {b}Anal{/b} in the lesbian context includes penetration with strap-ons and double-headed dildos, as well as scissoring.
                    "lesbian" : "{b}lesbian{/b}百合图片只包含女性。如果图像暗示男性的存在，请考虑改为标记双性恋。模棱两可的图像可以同时具有两个标签。\n百合语境中{b}性交{/b}和{b}肛交{/b}包括用穿戴假阴茎和双头假阳具的插入，以及剪刀式。"
                    }

    tag_special_help = {
                        "happy" : "开心。仅在她的情绪高涨或她爱玩家时才会显示。（在训练期间）",
                        "neutral" : "平常。只有在她的情绪、爱和恐惧既不高也不低时才会表现出来。 这通常是不需要的。",
                        "sad" : "悲伤。仅在她情绪低落或她害怕玩家时才会显示。（在训练期间）",

                        "cosplay" : "cosplay。她穿着制服（护士、士兵、吉祥物……）。",
                        # 貌似这个被整合到了“cosplay”里面
                        "roleplay" : "角色扮演。她正在扮演一个角色或模仿某些东西（通常与cosplay配对）。",
                        "maid" : "服务员。她穿得像个女仆或仆人。也用于服务员和农场。",
                        "bunny" : "兔女郎。",
                        "swim" : "按摩师。她穿着泳装。也用于按摩师。",
                        "kimono" : "艺伎。这个女孩穿着传统服装。也用于艺妓。",

                        "strip" : "女孩正在脱衣服。",
                        "sing" : "舞娘。这个女孩在唱歌，在舞台上演奏音乐，或者打扮得像个偶像。也用于舞者。",
                        "fight" : "抵抗。用于防御攻击。",

                        # "libido" : "The picture is a more sexy variant, shown only when the girl's libido is high enough. Examples include revealing or slutty clothes, sexy underwear, provocative/horny/seductive facial expressions or poses, etc.",
                        "libido" : "性欲。图片是更性感的变体，只有在女孩的性欲足够高时才会显示。例子包括暴露或放荡的衣服、性感内衣、挑逗/淫荡/诱人的面部表情或姿势等。",
                        # "sensitivity" : "The girl is being touched lightly (hand, feather...), patted, looking dazed or vulnerable, being placed in an awkward position (like her skirt being lifted), etc.\nAlso tag the image with e.g. rest, service, lesbian, fondle, finger, ... if any of those tags apply.",
                        "sensitivity" : "敏感。女孩被轻轻触摸（手、羽毛……），被拍打，看起来茫然或脆弱，被放置在一个尴尬的位置（比如她的裙子被掀起）等。\n此外标签与图像例如休息、服务、百合、爱抚、手指……如果这些标签中的任何一个适用。",
                        # "obedience" : "The girl is doing some menial task. e.g. cleaning, washing, cooking, housework, polishing items, etc.\nSituations like the girl being submissive, kneeling, kowtowing, etc. are better tagged with 'fetish' or 'sub' instead.",
                        "obedience" : "服从。女孩正在做一些琐碎的工作。例如清洁、洗涤、做饭、做家务、擦亮物品等。\n女孩顺从、跪下、磕头等情况。最好用 'fetish'皮绳愉虐 或 'sub'顺从 标记。",
                        # "constitution" : "The picture shows the girl doing something improving her constitution or fitness. e.g. running, doing sports, lifting weights, gymnastics, etc.",
                        "constitution" : "体格。女孩正在做一些改善体质或健康的事情。例如跑步、做运动、举重、体操等。",

                        # "public" : "She is in a publicly-accessible place (street, park, beach, tavern, hallway, restroom...), where bystanders might see her or there's some risk of being caught. Can be used for both sexual and non-sexual images. Use location tags if applicable.",
                        "public" : "她在公众可以进入的地方（街道、公园、海滩、小酒馆、走廊、洗手间……），旁观者可能会在那里看到她或有被抓住的风险。可用于性和非性图片。如果应用请使用位置标签。",

                        # "toy" : Toy means any kind of sexual toy, like dildos or buttplugs. Unlike 'machine', toys get used by the girl or her partner, and do not move on their own. (except stationary movement; vibrators count as toys)
                        "toy" : "玩具是指任何类型的性玩具，如假阳具或插塞。与“机器”不同，玩具由女孩或她的伴侣使用，不会自行使用。（静止运动除外；振动棒算作玩具）",
                        # 貌似没有这个标签，估计被整合到了“constitution”这个里面
                        "run" : "这个女孩看起来像是在奔跑。",
                        "dildo" : "振动棒。一种玩具。阴茎状，通常插入屁股或阴部。",
                        "vibrator" : "震动用品。一种玩具。各种形状，通常不插入。",
                        "beads" : "肛珠。一种玩具。",
                        "plug" : "肛塞。一种玩具。",
                        # "strap-on" : "A contraption allowing a female to use a cock-like dildo to fuck another female. Alternatively, can be used for futa pictures.",
                        "strap-on" : "穿戴假阴茎。一种允许女性使用像公鸡一样的假阳具来操另一位女性的装置。或者也可以用于双打图片。",

                        "dirty" : "邋遢。她在地板上被污物弄脏了，或者其他肮脏的环境。",
                        "wet" : "湿漉。她身上覆盖着大量的液体（水、油或类似物）。",
                        "dom" : "强势。她是占主导地位的女孩或摆出占主导地位的姿势。",
                        "sub" : "顺从。她正在顺从或处于屈辱的姿势。",

                        "kiss" : "她在接吻（脸红的照片也可以）。",
                        "fondle" : "被抚弄奶子。有人抚弄她的乳房。",
                        "grope" : "被摸屁股。有人在摸她的屁股。",
                        "finger" : "被抚摸。有人用一根或几根手指触摸或用手指抚摸她的私处。",
                        "masturbate" : "自慰。她在自慰（她自己）。",

                        "handjob" : "手交。她正在给一个男性(或很少是女性)伴侣手淫。",
                        "titjob" : "乳交。",
                        "footjob" : "足交。她用她的脚取悦她的伴侣。",
                        "oral" : "口交。涵盖所有类型的口交(与男性和女性伴侣)。",
                        "deep" : "深喉咙。",
                        "sixty-nine" : "69。",

                        "doggy" : "后背位。她在被从后面做爱。",
                        "cowgirl" : "骑乘位。她在上面做爱。",
                        "piledriver" : "她被颠倒了。（女孩被压在身下，从上面插入）",
                        "spooning" : "侧身位。她从后面被侧身做爱。",
                        "double" : "双穴插入。她同时被2只阴茎插入（一个洞或两个洞）。",

                        "bondage" : "绳缚。她脱不开身。",
                        "gag" : "口球。她的嘴被堵住了，不能说话。",
                        "spanking" : "打屁股。",
                        "rimming" : "毒龙钻。她在舔她搭档的屁股。",
                        "lactation" : "强制泌乳。乳汁状的物质从她的奶子里流出来。",
                        "watersports" : "“水”类运动包括“黄金淋浴”和其他“泌尿/公厕”内容（卑微的请求:不要太依赖这个）",
                        "enema" : "灌肠。",

                        "cumshot" : "射精。射精和它的衍生物包括男性射精在她身体的任何地方。",
                        "on-body" : "射在她的身上。",
                        "on-face" : "射在她的脸上。",
                        "in-hair" : "射在她的头发上。",
                        "in-mouth" : "射在她的嘴里。",
                        "inside" : "她在里面被射精（阴茎在里面）。",
                        "creampie" : "精液从她的私处漏出（里面没有阴茎）。",
                        "bukkake" : "多个男性在她脸上射精。",
                        # "cum-shower" : "An explosion of cum, not limited to her face.",
                        "cum-shower" : "迸发出的精液，不限于她的脸上。",

                        # "orgasm" : "She is cumming (ahegao pictures do nicely).",
                        "orgasm" : "高潮。她去了（阿嘿颜的图片很适合）。",
                        "denied" : "禁止高潮。她想高潮但做不到。",
                        "squirt" : "潮吹。从她的私处中喷出汁液（通常伴随着性高潮）。",

                        # 下面几个貌似没有显示标签？
                        "penis worship" : "她非常照顾某人的鸡巴（通常与手交配对）。",
                        "insults" : "她被虐待或侮辱。",
                        "irrumatio" : "强迫深喉(喉咙做爱)。",
        } # Changes: penis w --> HJ, roleplay --> Cosplay, ass-to-mouth --> cim, insults --> sub, irrumatio --> DT, swa --> cim, run --> constitution


    ## Sanity Check ##
    sanity_check() # Always do this at the end of adding new tags, it also recalculates important variables
