#### TAG DICTIONARY : Converts old tag (strings found in picture filename) to new tag(s) (used in game)

# <Chris12 - Tagsets>
init -3 python:

    img_bg = Frame("gui/img_bg.png", 0, 0, tile="integer")

    # use add_tag_hotkey() to make sure you do not overwrite existing hotkeys.
    tag_hotkeys = {
        "p" : "profile", 
        "t" : "portrait", 
        "w" : "waitress", 
        "d" : "dancer", 
        "m" : "masseuse", 
        "h" : "geisha", 
        "r" : "rest", 
        "n" : "naked", 
        "s" : "service", 
        "x" : "sex", 
        "a" : "anal", 
        "f" : "fetish", 
        "g" : "group", 
        "b" : "bisexual", 
        "l" : "lesbian",
        "i" : "big", 
        "e" : "beast", 
        "c" : "machine", 
        "y" : "toy", 
        "o" : "monster", 
    }
    
    def add_tag_hotkey(key, tag):
        if len(key) != 1 : raise Exception("add_tag_hotkey key '" + key + "' is not exactly one character!")
        key = key.lower()
        if key in tag_hotkeys: raise Exception("Hotkey '" + key + "' already bound to '" + tag_hotkeys[key] + "'")
        tag_hotkeys[key] = tag
# </Chris12 - Tagsets>

init -2 python:
    
    # tag_dict now serves as a way to add additional 'tags light'. Basically, those tags get kept if they are already in the filename, but no buttons are available to actively influence them.
    tag_dict = {
                "gallery" : "gallery", # Used as a background for the girl's CG gallery
                "ecchi" : ("rest", "libido")
    }

    
    ## END OF BK ORIGINAL TAGGING TOOL

    # bk_autoadds is used to keep the rating calculation in-line with BKs. E.g. lesbian automatically gets a bisexual tag in BK

    BK_AUTOADDS = (
        ("lesbian", "bisexual"),
        ("nature", "public"),
        ("beach", "public"),
        ("town", "public")
    )
    
    tag_dict["_trash"] = "ignore", # Change this if you want to be able to edit trash pictures

    sorted_tag_dict_keys = sorted(tag_dict.keys(), key = lambda x : -len(x)) # gets regenerated by sanity_check()


    # With sorting_dict, you can manually override order/order2.
    sorting_dict = {
                    "portrait" : (-10, 0), # This is an example, making the portrait tag come before profile in the file name
                    "profile" : (-10, 1),
                    "constitution" : (0, 55),
                    "fight" : (0, 56),
                    "obedience" : (0, 57),
                    }
    
    #### Base values
    
    VIDEOFORMATS = (".webm", ".mpg", ".mkv", ".avi", ".mp4")
    IMGFORMATS = (".jpg", ".jpeg", ".png", ".bmp", ".gif", ".webp", ".avif") + VIDEOFORMATS
    
    girl_list = []
    search_words = ""
    copy_tags = None
    
    
    # Buttons get displayed in the same order as in the main_tags list. 
    # However, output order (in the filename) is determined by order/order2. (and can be overriden with sorting_dict)
    main_tags = [
        Tag(name="profile", order=0, order2=10, tagsets=[tagset_core], variants=("card","quest","shop")),
        Tag(name="portrait", order=0, order2=0, tagsets=[tagset_core]),
        Tag(name="", tagsets=[tagset_core]),
        Tag(name="waitress", order=0, order2=20, tagsets=[tagset_core], variants="wait"),
        Tag(name="dancer", order=0, order2=30, tagsets=[tagset_core], variants="danc"),
        Tag(name="masseuse", order=0, order2=40, tagsets=[tagset_core], variants="mass"),
        Tag(name="geisha", order=0, order2=50, tagsets=[tagset_core], variants="etiquette"),
        Tag(name="", tagsets=[tagset_core]),
        Tag(name="rest", order=0, order2=60, tagsets=[tagset_core]),
        Tag(name="naked", order=0, order2=200, tagsets=[tagset_core], variants="nude"),
        Tag(name="", tagsets=[tagset_core]),
        Tag(name="service", order=0, order2=230, tagsets=[tagset_core]),
        Tag(name="sex", order=0, order2=240, tagsets=[tagset_core], variants=("fuck", "xxx")),
        Tag(name="anal", order=0, order2=250, tagsets=[tagset_core]),
        Tag(name="fetish", order=0, order2=260, tagsets=[tagset_core], variants="hardcore"),
        Tag(name="", tagsets=[tagset_core]),
        Tag(name="lesbian", order=0, order2=225, tagsets=[tagset_core]),
        Tag(name="bisexual", order=0, order2=220, tagsets=[tagset_core], variants="bis"),
        Tag(name="group", order=0, order2=210, tagsets=[tagset_core]),
        Tag(name="", tagsets=[tagset_core]),
        Tag(name="big", order=0, order2=110, tagsets=[tagset_core], variants="stallion"),
        Tag(name="beast", order=0, order2=120, tagsets=[tagset_core], variants="best"),
        Tag(name="machine", order=0, order2=130, tagsets=[tagset_core]),
        Tag(name="monster", order=0, order2=140, tagsets=[tagset_core]),
        Tag(name="", tagsets=[tagset_core])
    ]

    main_tags_idx = {tag.name : num for num, tag in enumerate(main_tags) if tag is not None and tag.name != ""} # gets regenerated by sanity_check()
    
    # Don't touch the following lines, they are important for girl rating.
    
    normal_tags = ["profile", "portrait", "rest", "waitress", "dancer", "masseuse", "geisha"]
    all_sex_acts = ["service", "sex", "anal", "fetish"]
    extended_sex_acts = ["naked", "service", "sex", "anal", "fetish", "bisexual", "group"] # Don't add "lesbian" here, ruins the rating
    all_farm_tags = ["big", "beast", "monster", "machine"]
    
    #### Main buttons
    
    tag_button_dict = { "profile" : "{u}P{/u}rofile", 
                        "portrait" : "Por{u}t{/u}rait", 
                        "waitress" : "{u}W{/u}aitress", 
                        "dancer" : "{u}D{/u}ancer", 
                        "masseuse" : "{u}M{/u}asseuse", 
                        "geisha" : "Geis{u}h{/u}a",
                        "rest" : "{u}R{/u}est",
                        "naked" : "{u}N{/u}aked", 
                        "service" : "{u}S{/u}ervice", 
                        "sex" : "Se{u}x{/u}", 
                        "anal" : "{u}A{/u}nal", 
                        "fetish" : "{u}F{/u}etish", 
                        "lesbian" : "{u}L{/u}esbian",
                        "bisexual" : "{u}B{/u}isexual (+F)", 
                        "group" : "{u}G{/u}roup (+M)", 
                        "big" : "B{u}i{/u}g dick", 
                        "beast" : "B{u}e{/u}ast", 
                        "machine" : "Ma{u}c{/u}hine", 
                        "monster" : "M{u}o{/u}nster"
                        }
    
    s_acts = ["service", "sex", "anal", "group", "fetish", "bisexual"]
    
    # The optional_tag_dict is specific to this naming tool. It sets some rules for when to show/hide optional tags
    optional_tags = [
            Tag(name="happy", order=7, order2=1),
            Tag(name="neutral", order=7, order2=2),
            Tag(name="sad", order=7, order2=3),
       
            Tag(name="cosplay", order=10, order2=0, variants=("roleplay", "role")),
            Tag(name="maid", _or=("profile", "portrait", "waitress"), order=10, order2=1, auto_add="waitress"),
            Tag(name="bunny", _or=("profile", "portrait", "waitress"), order=10, order2=1, auto_add="waitress"),
            Tag(name="swim", _or=("profile", "portrait", "masseuse", "rest"), order=10, order2=2),
            Tag(name="kimono", _or=("profile", "portrait", "geisha"), order=10, order2=3, auto_add="geisha"),
            
            Tag(name="strip", order=15, order2=1, fix_name="stripping"),
            Tag(name="sing", order=15, _or="dancer", _not = s_acts+all_farm_tags, order2=2, auto_add="dancer"),
            Tag(name="fight", order=15, _not = s_acts+all_farm_tags, order2=3, variants=["combat", "battle"]),
        
            Tag(name="libido", order=20, order2=1),
            Tag(name="sensitivity", order=20, order2=2, btn_text_size=19),
            Tag(name="obedience", _not = s_acts, order=20, order2=3, btn_text_size=19),
            Tag(name="constitution", _not = s_acts, order=20, order2=4, variants="run", btn_text_size = 17),

            Tag(name="public", order=25, order2=0, fix_name="public acts"),
        
            Tag(name="toy", order=30, order2=0),
            Tag(name="dildo", _or="toy", order=30, order2=1, fix_name="dildos", auto_add="toy", variants="dild"),
            Tag(name="vibrator", _or=("fetish", "toy"), order=30, order2=2, fix_name="vibrators", auto_add="toy", variants="vibr"),
            Tag(name="beads", _or=("fetish", "anal", "toy"), order=30, order2=3, auto_add="toy", variants="bead"),
            Tag(name="plug", _or=("fetish", "anal", "toy"), order=30, order2=4, fix_name="plugs", auto_add="toy"),
            Tag(name="strap-on", _or=("bisexual", "lesbian", "group"), _and=("toy"), order=30, order2=9, fix_name="strap-ons", variants="strap"),
        
            Tag(name="dirty", _or=extended_sex_acts, order=40, order2=12, fix_name="dirty sex"),
            Tag(name="wet", order=40, order2=14, variants="oil"),
            Tag(name="dom", order=40, order2=15, fix_name="femdom"),
            Tag(name="sub", order=40, order2=16, fix_name="submission", variants=("humiliat", "insults")),
        
            Tag(name="kiss", order=50, order2=1, fix_name="kissing"),
            Tag(name="fondle", _or = s_acts + ["naked"], order=50, order2=2, fix_name="fondling her boobs", variants="fondl"),
            Tag(name="grope", _or = s_acts + ["naked"], order=50, order2=3, fix_name="groping her ass", variants="grop"),
            Tag(name="finger", _or=("naked", "service", "bisexual", "fetish", "group"), order=50, order2=4, fix_name="fingering"),
            Tag(name="masturbate", _or = ("rest", "service", "naked", "sex"), order=50, order2=5, shorthand="mast", fix_name="masturbation", btn_text_size=17),
        
            Tag(name="handjob", _or=("service", "group"), order=60, order2=4, fix_name="handjobs", variants=("hand", "penis worship", "penis-worship", "penis_worship", "penisworship", "penis w", "penis-w", "penis_w", "penisw")),
            Tag(name="titjob", _or=("service", "group"), order=60, order2=5, fix_name="titjobs", variants=("titj", "ttj", "tits", "titty")),
            Tag(name="footjob", _or=("service", "fetish"), order=60, order2=6, fix_name="footjobs", variants=("foot", "fj")),
            Tag(name="oral", _or=("service", "bisexual", "group"), order=60, order2=7, variants=("blowjob", "bj")),
            Tag(name="deep", _or=("service", "group"), order=60, order2=8, fix_name="deep throat", variants=("irru", "dt")),
            Tag(name="sixty-nine", _or=("service", "bisexual"), order=60, order2=9, variants=("69 ", "sixty"), fix_name="69"),

            Tag(name="doggy", _or=("sex", "anal"), order=70, order2=14, fix_name="doggy style"),
            Tag(name="cowgirl", _or=("sex", "anal"), order=70, order2=15, variants="cowg"),
            Tag(name="piledriver", _or=("sex", "anal"), order=70, order2=16, variants = "pile"),
            Tag(name="spooning", _or=("sex", "anal"), order=70, order2=17, variants = "spoon"),
            Tag(name="double", _or="group", order=70, order2=18, fix_name="double penetration"),
        
            Tag(name="bondage", _or=("fetish", "naked"), order=80, order2=1, variants="bdsm"),
            Tag(name="gag", _or=("fetish", "naked"), order=80, order2=2, fix_name="gags"),
            Tag(name="spanking", _or=("fetish", "anal"), order=80, order2=3, variants="spank"),
            Tag(name="rimming", _or=("service", "fetish"), order=80, order2=4, variants="rim"),
            Tag(name="fisting", _or=("fetish", "bisexual", "anal"), order=80, order2=5, variants="fist"),
            Tag(name="lactation", _or=("naked", "fetish"), order=80, order2=6, variants="lact"),
            Tag(name="watersports", _or=("fetish", "sex"), order=80, order2=7, fix_name="watersports", lbl="Watersp", variants="watersp"),
            Tag(name="enema", _or=("fetish", "anal", "toy"), order=80, order2=8, fix_name="enemas"),
        
            Tag(name="cumshot", order=90, order2=1),
            Tag(name="on-body", _or="cumshot", order=90, order2=2, shorthand="cob", fix_name="cum on body", variants="body", auto_add="cumshot"),
            Tag(name="on-face", _or="cumshot", order=90, order2=3, shorthand="cof", fix_name="cum on face", variants="face", auto_add="cumshot"),
            Tag(name="in-hair", _or="cumshot", order=90, order2=4, shorthand="cih", fix_name="cum in hair", variants="hair", auto_add="cumshot"),
            Tag(name="in-mouth", _or="cumshot", order=90, order2=5, shorthand="cim", fix_name="cum in mouth", variants=("mouth", "swallow"), auto_add="cumshot"),
            Tag(name="inside", _or=("sex", "anal", "group"), _and="cumshot", order=90, order2=8, shorthand="cin", fix_name="cum inside", auto_add="cumshot"),
            Tag(name="creampie", _or=("sex", "anal", "group"), _and="cumshot", order=90, order2=9, variants="cream", auto_add="cumshot"),
            Tag(name="bukkake", _or=("bisexual", "group"), _and="cumshot", order=90, order2=10, shorthand="bukk", auto_add="cumshot"),
            Tag(name="cum-shower", _or=("bisexual", "group"), _and="cumshot", order=90, order2=11, lbl="Cumshower", variants=("cum shower", "shower"), auto_add="cumshot", btn_text_size=17),
        
            Tag(name="orgasm", order=100, _not="denied", order2=1, fix_name="multiple orgasms"),
            Tag(name="denied", order=100, _not="orgasm", order2=2, fix_name="denied orgasm"),
            Tag(name="squirt", _or="orgasm", order=100, order2=3, fix_name="squirting", auto_add="orgasm"),
    ]
    optional_tags = sorted(optional_tags, key = lambda x: (x.order, x.order2)) # gets regenerated by sanity_check()
    optional_tag_dict = {tag.name : tag for tag in optional_tags} # gets regenerated by sanity_check()
    
    all_tags_dict = {tag.name : tag for tag in (main_tags + optional_tags)} # gets regenerated by sanity_check()
    
    # This is a copy of BK's original Fixation dictionary (for girl pack stats calculations)
    fix_dict = {
                "stripping" : Fixation("stripping", acts=("naked", "sex", "bisexual"), step=1, attribute="repressed", tag_list=("strip", "naked", "dancer"), not_list=["naked"]),
                "public acts" : Fixation("public acts", acts=("naked", "service", "sex", "group"), step=1, attribute="extravert", tag_list=(["public"],)),
                "cosplay" : Fixation("cosplay", acts=("naked", "fetish", "bisexual"), step=1, attribute="extravert", tag_list=(["cosplay"], ["maid", "kimono"], ["swim", "waitress", "dancer"]), not_list=["naked"],),
                "dildos" : Fixation("dildos", acts=("sex", "anal", "bisexual"), step=1, attribute="introvert", tag_list=(["dildo"], ["toy"],)),
                "vibrators" : Fixation("vibrators", acts=("naked", "fetish", "bisexual"), step=1, attribute="introvert", tag_list=(["vibrator"], ["toy"],)),
                "dirty sex" : Fixation("dirty sex", acts=("sex", "fetish", "group"), step=1, attribute="sub", tag_list=(["dirty"],)),
                "penis worship" : Fixation("penis worship", acts=("service", "group"), step=1, attribute="sub", tag_list=(["handjob"], ["big"],)),
                "bondage" : Fixation("bondage", acts=("fetish", "naked"), step=1, attribute="sub", tag_list=(["bondage"],)),
                "oil" : Fixation("oil", acts=("group", "anal"), step=1, attribute="extravert", tag_list=(["wet"],)),
                "wet" : Fixation("wet", acts=("naked", "sex", "bisexual"), step=1, attribute="extravert", tag_list=(["wet"],)),
                "submission" : Fixation("submission", acts=("service", "fetish", "bisexual"), step=1, attribute="sub", tag_list=(["sub"],)),
                "femdom" : Fixation("femdom", acts=("bisexual", "sex", "service"), step=1, attribute="dom", tag_list=(["dom"],)),
                "gags" : Fixation("gags", acts=("fetish", "naked"), step=1, attribute="introvert", tag_list=(["gag"], ["bondage"],)),
                "strap-ons" : Fixation("strap-ons", acts=("bisexual", "group"), step=1, attribute="dom", tag_list=(["strap-on"], ["lesbian"], ["toy"],)),
                "roleplay" : Fixation("roleplay", acts=("naked", "sex", "fetish"), step=1, attribute="extravert", tag_list=(["cosplay"], ["maid", "kimono"], ["swim", "waitress", "dancer"])),
                "plugs" : Fixation("plugs", acts=("naked", "anal"), step=1, attribute="repressed", tag_list=(["plug"], ["toy"],)),
                "enemas" : Fixation("enemas", acts=("group", "anal"), step=1, attribute="materialist", tag_list=(["enema"], ["toy"],)),
                "beads" : Fixation("beads", acts=("anal"), step=1, attribute="introvert", tag_list=(["beads"], ["toy"],)),
                
                "masturbation" : Fixation("masturbation", acts=("service", "naked", "sex"), step=2, attribute="extravert", tag_list=(["masturbate"], ["naked"],)),
                "fingering" : Fixation("fingering", acts=("naked", "fetish", "bisexual", "group"), step=2, attribute="lewd", tag_list=(["finger"],)),
                "handjobs" : Fixation("handjobs", acts=("service", "group"), step=2, attribute="repressed", tag_list=(["handjob"],)),
                "cunnilingus" : Fixation("cunnilingus", acts=("service", "bisexual"), step=2, attribute="introvert", tag_list=(["cunnilingus"],["finger"])),
                "oral" : Fixation("oral", acts=("service", "bisexual", "group"), step=2, tag_list=(["oral"],)),
                "irrumatio" : Fixation("irrumatio", acts=("fetish"), step=2, attribute="sub", tag_list=(["deep"], ["oral"],)),
                "deep throat" : Fixation("deep throat", acts=("service", "group"), step=2, attribute="sub", tag_list=(["deep"], ["oral"],)),
                "titjobs" : Fixation("titjobs", acts=("service", "group"), step=2, attribute="extravert", tag_list=(["titjob"],)),
                "footjobs" : Fixation("footjobs", acts=("service", "fetish"), step=2, attribute="dom", tag_list=(["footjob"],)),
                "double penetration" : Fixation("double penetration", acts=("group"), step=2, attribute="lewd", tag_list=(["double"],)),
                "fisting" : Fixation("fisting", acts=("fetish", "bisexual", "anal"), step=2, attribute="lewd", tag_list=(["fisting"], ["finger"])),
                "insults" : Fixation("insults", acts=("fetish", "naked"), step=2, attribute="sub", tag_list=(["sub"],)),
                "69" : Fixation("69", acts=("service", "bisexual"), step=2, attribute="dom", tag_list=(["sixty-nine"], ["oral"],)),
                "watersports" : Fixation("watersports", acts=("fetish", "sex"), step=2, attribute="sub", tag_list=(["watersports"], ["squirt"],)),
                "ass-to-mouth" : Fixation("ass-to-mouth", acts=("anal", "group"), step=2, attribute="sub", tag_list=(["in-mouth"], ["oral"],)),
                "kissing" : Fixation("kissing", acts=("naked", "sex", "bisexual"), step=2, attribute="idealist", tag_list=(["kiss"],)),
                "spanking" : Fixation("spanking", acts=("fetish", "anal"), step=2, attribute="sub", tag_list=(["spanking"], ["sub"],)),
                "rimming" : Fixation("rimming", acts=("service", "fetish"), step=2, attribute="sub", tag_list=(["rimming"],)),
                "fondling her boobs" : Fixation("fondling her boobs", short_name = "fondling", acts=("naked", "sex", "bisexual", "group"), step=2, tag_list=(["fondle"],)),
                "groping her ass" : Fixation("groping her ass", short_name = "groping", acts=("naked", "anal", "bisexual", "group"), step=2, tag_list=(["grope"],)),
                "lactation" : Fixation("lactation", acts=("naked", "fetish"), step=2, attribute="extravert", tag_list=(["lactation"], ["titjob"],)),
                "doggy style" : Fixation("doggy style", acts=("sex", "anal"), step=2, attribute="lewd", tag_list=(["doggy"],)),
                "cowgirl" : Fixation("cowgirl", acts=("sex", "anal"), step=2, attribute="dom", tag_list=(["cowgirl"],)),
                "piledriver" : Fixation("piledriver", acts=("sex", "anal"), step=2, attribute="materialist", tag_list=(["piledriver"],)),
                "spooning" : Fixation("spooning", acts=("sex", "anal"), step=2, attribute="idealist", tag_list=(["spooning"],)),
                
                "bukkake" : Fixation("bukkake", acts=("bisexual", "group"), step=3, attribute="lewd", tag_list=(["bukkake"], ["on-face"], ["cumshot"],)),
                "cum in mouth" : Fixation("cum in mouth", acts=("service", "anal", "bisexual"), step=3, attribute="lewd", tag_list=(["in-mouth"], ["oral"],)),
                "cum on face" : Fixation("cum on face", acts=("service", "sex", "fetish"), step=3, attribute="sub", tag_list=(["on-face"], ["bukkake"], ["cumshot"],)),
                "cum in hair" : Fixation("cum in hair", acts=("service", "fetish"), step=3, attribute="sub", tag_list=(["in-hair"], ["on-face", "bukkake"], ["cumshot"],)),
                "cum on body" : Fixation("cum on body", acts=("sex", "anal", "service"), step=3, attribute="dom", tag_list=(["on-body"], ["cumshot"],)),
                "cum shower" : Fixation("cum shower", acts=("bisexual", "group"), step=3, attribute="sub", tag_list=(["cum-shower"], ["on-body", "in-hair"], ["cumshot"],)),
                "swallowing" : Fixation("swallowing", acts=("service", "fetish"), step=3, attribute="materialist", tag_list=(["in-mouth"], ["deep"], ["oral"],)),
                "creampie" : Fixation("creampie", acts=("sex", "anal", "group"), step=3, attribute="extravert", tag_list=(["creampie"], ["inside"],)),
                "cum inside" : Fixation("cum inside", acts=("sex", "anal"), step=3, attribute="introvert", tag_list=(["inside"], ["creampie"],)),
                "multiple orgasms" : Fixation("multiple orgasms", acts=("group", "bisexual"), step=3, attribute="lewd", tag_list=(["orgasm"],)),
                "denied orgasm" : Fixation("denied orgasm", acts=("anal", "fetish", "bisexual"), step=3, attribute="sub", tag_list=(["denied"],)),
                "squirting" : Fixation("squirting", acts=("service", "sex", "bisexual"), step=3, attribute="extravert", tag_list=(["squirt"], ["watersport", "orgasm"],)),
                }
    
    
    
    event_color = {"special": "{color=#FF9900}%s{/color}",
                   "good": "{color=#009874}%s{/color}",
                   "a little good": "{color=#66FF99}%s{/color}",
                   "average": "{color=#FFFF33}%s{/color}",
                   "a little bad": "{color=#F78181}%s{/color}",
                   "bad": "{color=#FF0000}%s{/color}",
                   "fear": "{color=#9933FF}%s{/color}",
                   }
    
    
    tag_main_help = {
                    "machine" : "Machine images show the girl being with a robot or mechanical contraption moving autonomously.\nFor ordinary sex toys, including vibrators, use the 'toy' tag instead.",
                    "bisexual" : "At least one additional woman is in the image. Pictures with only women should be tagged 'lesbian' instead.\nBisexual pictures make use of extra sexual tags, e.g. you can tag 'bisexual sex fetish'.",
                    "group" : "At least one additional man is in the image. Combine this tag with 'bisexual' in cases of additional men AND women.\nGroup pictures make use of extra sexual tags, e.g. you can tag 'group service anal'.\nThe 'group' tag also applies to groups of non-human minions at the farm.",
                    ("profile", "portrait") : "{b}Profile{/b} pictures show the girl's whole body, {b}Portraits{/b} focus on the face. These pictures should show only the girl, without other people. Profile and portrait pictures are used by default if no other matching picture is available. They should have both naked and non-naked versions. Optionally, they can have happy/sad/libido... versions",
                    "waitress" : "Waitress pictures should have both naked and non-naked versions.\nExamples include the girl serving food or drinks, cooking or cleaning.\nIf used with a sexual tag, will not show during normal work, but may show during work&whore and special events.",
                    "dancer" : "Dancer pictures should have both naked and non-naked versions.\nExamples include the girl dancing, singing, stripping, wearing a dancer-like outfit or lingerie.\nIf used with a sexual tag, will not show during normal work, but may show during work&whore and special events.",
                    "masseuse" : "Masseuse pictures should have both naked and non-naked versions.\nExamples include the girl wearing only a towel or swimsuit, or near a bath or pool.\nIf used with a sexual tag, will not show during normal work, but may show during work&whore and special events.",
                    "geisha" : "Geisha pictures should have both naked and non-naked versions.\nExamples include the girl wearing a traditional or fancy-looking outfit, such as a kimono or cocktail dress.\nIf used with a sexual tag, will not show during normal work, but may show during work&whore and special events.",
                    "rest" : "Rest pictures should have both naked and non-naked versions.\nExamples include laying down on a bed or resting on a chair.\nWill not show during normal resting if used with a sexual tag.",
                    "naked" : "The girl is topless, her genitals/asshole are shown, or she is fully naked.\nUse the 'strip' or 'libido' tags instead for more ambiguous situations.\nHaving naked variations of profile, portrait, rest, job and farm tags is strongly recommended.\nThe naked tag is not recommended for sexual pictures (all sexual pictures are assumed to be naked).",
                    ("beast", "monster") : "Beasts are animals from the natural world, monsters are supernatural. Beast and Monster pictures are restricted in-game to the Farm. Farm pictures do not generally make use of optional tags.",
                    "service" : "Service pictures include masturbation, handjobs, blowjobs, titjobs and other kinds of vanilla foreplay acts.",
                    "fetish" : "Fetish pictures display various kinks that do not easily fit in other sex categories, such as bondage, fisting or footjobs.",
                    ("sex", "anal") : "Sex involves sexual penetration of the vagina by a male genital organ. Anal involves sexual penetration of the anus by a male genital organ. (Duh.) Apply both 'sex' and 'anal' to indicate 'could be either'.\nThe tags can also be applied if the penetration is about to happen, or has obviously happened earlier (e.g. creampie situations). Lesbian images have slightly adjusted conditions.",
                    "big" : "Big dick pictures involve a partner with a larger-than-life cock. Alternatively, a partner with a larger-than-life body.",
                    "lesbian" : "Lesbian pictures only feature females. If the presence of a male is implied by the image, consider tagging bisexual instead. Ambiguous images can feature both tags.\n{b}Sex{/b} and {b}Anal{/b} in the lesbian context includes penetration with strap-ons and double-headed dildos, as well as scissoring."
                    }
                    
    tag_special_help = {
                        "dom" : "She is the dominating partner or striking a dominating pose.",
                        "sub" : "She is being submissive or in a humiliating posture.",
                        "grope" : "Her ass is being groped by someone.",
                        "fondle" : "Her tits are being fondled by someone.",
                        "denied" : "She wants to cum but can't.",
                        "cowgirl" : "She is on top while fucking.",
                        "doggy" : "She is being fucked from behind.",
                        "piledriver" : "She is being fucked upside down.",
                        "spooning" : "She is being fucked sideways, from behind.",
                        "wet" : "She is covered with a good amount of liquid (water, oil or similar).",
                        "cosplay" : "She is wearing a uniform (nurse, soldier, mascot...).",
                        "roleplay" : "She is playing a role or mimicking something (usually paired with cosplay).",
                        "penis worship" : "She is taking great care of someone's dick (usually paired with handjob).",
                        "dirty" : "She is on the floor, smeared with filth, or any other kind of dirty environment.",
                        "public" : "She is in a publicly-accessible place (street, park, beach, tavern, hallway, restroom...), where bystanders might see her or there's some risk of being caught. Can be used for both sexual and non-sexual images. Use location tags if applicable.",
                        "watersports" : "Watersports involves 'golden showers' and other uro/toilet content (humble request: do not lean too far on this one)",
                        "cumshot" : "Cumshot and its derivatives involve male cum anywhere on her body.",
                        "on-body" : "Cum on her body.",
                        "on-face" : "Cum on her face.",
                        "in-hair" : "Cum in her hair.",
                        "in-mouth" : "Cum in her mouth.",
                        "bukkake" : "Multiple partners cumming on her face.",
                        "cum-shower" : "An explosion of cum, not limited to her face.",
                        "finger" : "Someone is touching or fingering her pussy with one or several fingers.",
                        "squirt" : "Juice squirting out of her pussy (usually paired with orgasm).",
                        "double" : "She is being penetrated by at least 2 cocks at the same time (in anus and/or vagina).",
                        "deep" : "Deep-throat.",
                        "masturbate" : "She is masturbating (herself).",
                        "inside" : "She is being cummed inside (dick is inside).",
                        "creampie" : "Cum is leaking from her pussy (no dick is inside).",
                        "kiss" : "She is kissing (a blushing picture can also do).",
                        "toy" : "Toy means any kind of sexual toy, like dildos or buttplugs. Unlike 'machine', toys get used by the girl or her partner, and do not move on their own. (except stationary movement; vibrators count as toys)",
                        "maid" : "She is dressed like a maid or servant. Also used for waitress and the farm.",
                        "swim" : " She is dressed in a swimsuit. Also used for masseuse.",
                        "strip" : "The girl is taking her clothes off.",
                        "sing" : "The girl is singing, playing music on stage, or dressed like an idol. Also used for dancer.",
                        "kimono" : "The girl is wearing a traditional outfit. Also used for geisha.",
                        "run" : "The girl looks like she's running.",
                        "dildo" : "A type of toy. Dick-shaped, usually inserted in ass or pussy.",
                        "vibrator" : "A type of toy. Various shapes, usually not inserted.",
                        "beads" : "A type of toy. Anal beads.",
                        "plug" : "A type of toy. Anal plug.",
                        "strap-on" : "A contraption allowing a female to use a cock-like dildo to fuck another female. Alternatively, can be used for futa pictures.",
                        "insults" : "She is being abused or insulted.",
                        "bondage" : "She is tied up.",
                        "gag" : "Her mouth is blocked so that she cannot speak.",
                        "irrumatio" : "Forced deep-throat (throat-fucking).",
                        "handjob" : "She is giving a handjob to a male (or, rarely, female) partner.",
                        "oral" : "Covers all types of oral sex (with male and female partners).",
                        "rimming" : "She is licking her partner's ass.",
                        "lactation" : "Milk-like substance coming out of her tits.",
                        "orgasm" : "She is cumming (ahegao pictures do nicely).",
                        "footjob" : "She is using her feet to pleasure her partner.",
                        "happy" : "Will only display if her mood is high, or if she loves the player (during training).",
                        "sad" : "Will only display if her mood is low, or if she fears the player (during training).",
                        "neutral" : "Will only display if her mood, love and fear are neither high nor low. This is usually not needed.",
                        "libido" : "The picture is a more sexy variant, shown only when the girl's libido is high enough. Examples include revealing or slutty clothes, sexy underwear, provocative/horny/seductive facial expressions or poses, etc.",
                        "obedience" : "The girl is doing some menial task. e.g. cleaning, washing, cooking, housework, polishing items, etc.\nSituations like the girl being submissive, kneeling, kowtowing, etc. are better tagged with 'fetish' or 'sub' instead.",
                        "constitution" : "The picture shows the girl doing something improving her constitution or fitness. e.g. running, doing sports, lifting weights, gymnastics, etc.",
                        "sensitivity" : "The girl is being touched lightly (hand, feather...), patted, looking dazed or vulnerable, being placed in an awkward position (like her skirt being lifted), etc.\nAlso tag the image with e.g. rest, service, lesbian, fondle, finger, ... if any of those tags apply.",
                        "fight" : "Used when defending against an attack.",                        
                        
        } # Changes: penis w --> HJ, roleplay --> Cosplay, ass-to-mouth --> cim, insults --> sub, irrumatio --> DT, swa --> cim, run --> constitution
    

    ## Sanity Check ##
    sanity_check() # Always do this at the end of adding new tags, it also recalculates important variables