# TODO: Translation updated at 2024-04-27 18:30

translate schinese strings:

    # game/BKdeclarations.rpy:1528
    old "Image [index] of [count] locked."
    new "图片 [count] of [index] 尚未解锁。"

    # game/BKdeclarations.rpy:1569
    old "prev"
    new "上一页"

    # game/BKdeclarations.rpy:1570
    #old "next" 涉及if判断很多next
    #new "下一页"

    # game/BKdeclarations.rpy:1571
    old "slideshow"
    new "幻灯片"

    # game/BKdeclarations.rpy:1574
    old "return"
    new "返回"

    # game/BKdeclarations.rpy:1403
    old "CG - Game"
    new "CG - 游戏"

    # game/BKdeclarations.rpy:1405
    old "CG - Girl packs"
    new "CG - 女孩包"

    # game/BKdeclarations.rpy:1490
    old "IGNORED"
    new "忽略"

    # game/BKdeclarations.rpy:1497
    old "Page " 
    new "页面 "


###########################################################
#  ________  ________  ________        ___  ________      #
# |\   __  \|\   __  \|\   __  \      |\  \|\_____  \     #
# \ \  \|\  \ \  \|\  \ \  \|\  \     \ \  \\|___/  /|    #
#  \ \   ____\ \   _  _\ \  \\\  \  __ \ \  \   /  / /    #
#   \ \  \___|\ \  \\  \\ \  \\\  \|\  \\_\  \ /  /_/__   #
#    \ \__\    \ \__\\ _\\ \_______\ \________\\________\ #
#     \|__|     \|__|\|__|\|_______|\|________|\|_______| #
#                                                         #
#  This rpy file is generated by the project:             #
#  https://github.com/abse4411/projz_renpy_translation    #
###########################################################
